import { AppImages } from "./appImages";

 export const productsList = [
        {
            id: 1,
            name: "Case of the Giant Jackal",
            price: 20.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product1,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: []
        },
        {
            id: 2,
            name: "Case of the Giant Pygmy",
            price: "42.00 – 45.00",
            oldPrice: null,
            sale: true,
            image: AppImages.product2,
            description: "Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Red", "Blue"]
        },
        {
            id: 3,
            name: "Case of the Miniature",
            price: 16.0,
            oldPrice: 18.0,
            sale: true,
            image: AppImages.product3,
            description: "Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Green", "Yellow"]
        },
        {
            id: 4,
            name: "Clue of the Thirteenth",
            price: 45.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product4,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Gray"]
        }, {
            id: 1,
            name: "Case of the Giant Jackal",
            price: 20.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product1,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Black", "White"]
        },
        {
            id: 2,
            name: "Case of the Giant Pygmy",
            price: "42.00 – 45.00",
            oldPrice: null,
            sale: true,
            image: AppImages.product2,
            description: "Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Red", "Blue"]
        },
        {
            id: 3,
            name: "Case of the Miniature",
            price: 16.0,
            oldPrice: 18.0,
            sale: true,
            image: AppImages.product3,
            description: "Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Green", "Yellow"]
        },
        {
            id: 4,
            name: "Clue of the Thirteenth",
            price: 45.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product4,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Gray"]
        },
           {
            id: 1,
            name: "Case of the Giant Jackal",
            price: 20.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product1,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Black", "White"]
        },
        {
            id: 2,
            name: "Case of the Giant Pygmy",
            price: "42.00 – 45.00",
            oldPrice: null,
            sale: true,
            image: AppImages.product2,
            description: "Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Red", "Blue"]
        },
        {
            id: 3,
            name: "Case of the Miniature",
            price: 16.0,
            oldPrice: 18.0,
            sale: true,
            image: AppImages.product3,
            description: "Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Green", "Yellow"]
        },
        {
            id: 4,
            name: "Clue of the Thirteenth",
            price: 45.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product4,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Gray"]
        }, {
            id: 1,
            name: "Case of the Giant Jackal",
            price: 20.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product1,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Black", "White"]
        },
        {
            id: 2,
            name: "Case of the Giant Pygmy",
            price: "42.00 – 45.00",
            oldPrice: null,
            sale: true,
            image: AppImages.product2,
            description: "Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Red", "Blue"]
        },
        {
            id: 3,
            name: "Case of the Miniature",
            price: 16.0,
            oldPrice: 18.0,
            sale: true,
            image: AppImages.product3,
            description: "Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Green", "Yellow"]
        },
        {
            id: 4,
            name: "Clue of the Thirteenth",
            price: 45.0,
            oldPrice: null,
            sale: false,
            image: AppImages.product1,
            description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
            sizeAndFit: "The model (height 6′) is perfect for you.",
            materialAndCare: "100% Genuine. Machine-wash.",
            colors: ["Gray"]
        },
    ];